# Site settings
title: Nice Blog
name: Nice Blog # your name
email: wojciech.masarczyk@gmail.com 
description: >
    A simple blog about complex things. # this means to ignore newlines until "baseurl:"
baseurl: /SimpleBlog # the subpath of your site, e.g. /blog
url: e7mul.github.io # the base hostname & protocol for your site
twitter_username: # your Twitter username
github_username: # your Github username
disqus_username: # your disqus username

google-analytics: # add it if you have one

skillstree: false # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
